name: Upload auth-scheduled-backup extension

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Release Stage'
        required: true
        type: choice
        options:
          - alpha
          - beta
          - rc
          - stable

jobs:
  upload_extension:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate with Firebase
      run: |
        echo "${{ secrets.SERVICE_ACCOUNT_KEY }}" | base64 --decode > "$HOME/service-account-key.json"
        echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account-key.json" >> $GITHUB_ENV

    - name: Upload Firebase Extension
      run: |
        firebase ext:dev:upload ${{ secrets.FIREBASE_PUBLISHER_ID }}/${{ secrets.FIREBASE_EXTENSION_ID }} \
        --repo "https://github.com/50Fifty/auth-scheduled-backup" \
        --ref "main" \
        --stage ${{ github.event.inputs.stage }} \
        --force
          