name: Run integration tests

on:  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Change into functions directory
        run: cd functions
  
      - name: Install dependencies
        run: |
          cd functions
          npm install

      - name: Build
        run: |
          cd functions
          npm run build --if-present

      - name: Run tests
        run: |
          cd functions
          npm test
