name: Run unit and integration tests

on:  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
  
      - name: Install dependencies
        run: |
          cd functions
          npm install

      - name: Build
        run: |
          cd functions
          npm run build --if-present

      - name: Create serviceAccountKey.json
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: echo $SERVICE_ACCOUNT_KEY | base64 -di > ./functions/tests/configs/serviceAccountKey.json
        
      - name: Run unit tests
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          CRON_SCHEDULE: ${{ secrets.CRON_SCHEDULE }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PUBSUB_EMULATOR_ENDPOINT: ${{ secrets.PUBSUB_EMULATOR_ENDPOINT }}
        run: |
          cd functions
          npm run test:unit
      
      - name: Run integration tests
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          CRON_SCHEDULE: ${{ secrets.CRON_SCHEDULE }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PUBSUB_EMULATOR_ENDPOINT: ${{ secrets.PUBSUB_EMULATOR_ENDPOINT }}
        run: |
          npm install -g firebase-tools
          firebase emulators:exec \"cd functions && npm run test:system --exit\"
